DROP TABLE IF EXISTS carrier_claims;
CREATE TABLE IF NOT EXISTS carrier_claims (
    desynpuf_id        CHAR(16),
    clm_id             CHAR(15),
    clm_from_dt        CHAR(8),
    clm_thru_dt        CHAR(8),

    icd9_dgns_cd_1     VARCHAR(5),
    icd9_dgns_cd_2     VARCHAR(5),
    icd9_dgns_cd_3     VARCHAR(5),
    icd9_dgns_cd_4     VARCHAR(5),
    icd9_dgns_cd_5     VARCHAR(5),
    icd9_dgns_cd_6     VARCHAR(5),
    icd9_dgns_cd_7     VARCHAR(5),
    icd9_dgns_cd_8     VARCHAR(5),

    prf_physn_npi_1    CHAR(10),
    prf_physn_npi_2    CHAR(10),
    prf_physn_npi_3    CHAR(10),
    prf_physn_npi_4    CHAR(10),
    prf_physn_npi_5    CHAR(10),
    prf_physn_npi_6    CHAR(10),
    prf_physn_npi_7    CHAR(10),
    prf_physn_npi_8    CHAR(10),
    prf_physn_npi_9    CHAR(10),
    prf_physn_npi_10   CHAR(10),
    prf_physn_npi_11   CHAR(10),
    prf_physn_npi_12   CHAR(10),
    prf_physn_npi_13   CHAR(10),

    tax_num_1          CHAR(9),
    tax_num_2          CHAR(9),
    tax_num_3          CHAR(9),
    tax_num_4          CHAR(9),
    tax_num_5          CHAR(9),
    tax_num_6          CHAR(9),
    tax_num_7          CHAR(9),
    tax_num_8          CHAR(9),
    tax_num_9          CHAR(9),
    tax_num_10         CHAR(9),
    tax_num_11         CHAR(9),
    tax_num_12         CHAR(9),
    tax_num_13         CHAR(9),

    hcpcs_cd_1         CHAR(5),
    hcpcs_cd_2         CHAR(5),
    hcpcs_cd_3         CHAR(5),
    hcpcs_cd_4         CHAR(5),
    hcpcs_cd_5         CHAR(5),
    hcpcs_cd_6         CHAR(5),
    hcpcs_cd_7         CHAR(5),
    hcpcs_cd_8         CHAR(5),
    hcpcs_cd_9         CHAR(5),
    hcpcs_cd_10        CHAR(5),
    hcpcs_cd_11        CHAR(5),
    hcpcs_cd_12        CHAR(5),
    hcpcs_cd_13        CHAR(5),

    line_nch_pmt_amt_1    NUMERIC(12,2),
    line_nch_pmt_amt_2    NUMERIC(12,2),
    line_nch_pmt_amt_3    NUMERIC(12,2),
    line_nch_pmt_amt_4    NUMERIC(12,2),
    line_nch_pmt_amt_5    NUMERIC(12,2),
    line_nch_pmt_amt_6    NUMERIC(12,2),
    line_nch_pmt_amt_7    NUMERIC(12,2),
    line_nch_pmt_amt_8    NUMERIC(12,2),
    line_nch_pmt_amt_9    NUMERIC(12,2),
    line_nch_pmt_amt_10   NUMERIC(12,2),
    line_nch_pmt_amt_11   NUMERIC(12,2),
    line_nch_pmt_amt_12   NUMERIC(12,2),
    line_nch_pmt_amt_13   NUMERIC(12,2),

    line_bene_ptb_ddctbl_amt_1  NUMERIC(12,2),
    line_bene_ptb_ddctbl_amt_2  NUMERIC(12,2),
    line_bene_ptb_ddctbl_amt_3  NUMERIC(12,2),
    line_bene_ptb_ddctbl_amt_4  NUMERIC(12,2),
    line_bene_ptb_ddctbl_amt_5  NUMERIC(12,2),
    line_bene_ptb_ddctbl_amt_6  NUMERIC(12,2),
    line_bene_ptb_ddctbl_amt_7  NUMERIC(12,2),
    line_bene_ptb_ddctbl_amt_8  NUMERIC(12,2),
    line_bene_ptb_ddctbl_amt_9  NUMERIC(12,2),
    line_bene_ptb_ddctbl_amt_10 NUMERIC(12,2),
    line_bene_ptb_ddctbl_amt_11 NUMERIC(12,2),
    line_bene_ptb_ddctbl_amt_12 NUMERIC(12,2),
    line_bene_ptb_ddctbl_amt_13 NUMERIC(12,2),

    line_bene_prmry_pyr_pd_amt_1  NUMERIC(12,2),
    line_bene_prmry_pyr_pd_amt_2  NUMERIC(12,2),
    line_bene_prmry_pyr_pd_amt_3  NUMERIC(12,2),
    line_bene_prmry_pyr_pd_amt_4  NUMERIC(12,2),
    line_bene_prmry_pyr_pd_amt_5  NUMERIC(12,2),
    line_bene_prmry_pyr_pd_amt_6  NUMERIC(12,2),
    line_bene_prmry_pyr_pd_amt_7  NUMERIC(12,2),
    line_bene_prmry_pyr_pd_amt_8  NUMERIC(12,2),
    line_bene_prmry_pyr_pd_amt_9  NUMERIC(12,2),
    line_bene_prmry_pyr_pd_amt_10 NUMERIC(12,2),
    line_bene_prmry_pyr_pd_amt_11 NUMERIC(12,2),
    line_bene_prmry_pyr_pd_amt_12 NUMERIC(12,2),
    line_bene_prmry_pyr_pd_amt_13 NUMERIC(12,2),

    line_coinsrnc_amt_1   NUMERIC(12,2),
    line_coinsrnc_amt_2   NUMERIC(12,2),
    line_coinsrnc_amt_3   NUMERIC(12,2),
    line_coinsrnc_amt_4   NUMERIC(12,2),
    line_coinsrnc_amt_5   NUMERIC(12,2),
    line_coinsrnc_amt_6   NUMERIC(12,2),
    line_coinsrnc_amt_7   NUMERIC(12,2),
    line_coinsrnc_amt_8   NUMERIC(12,2),
    line_coinsrnc_amt_9   NUMERIC(12,2),
    line_coinsrnc_amt_10  NUMERIC(12,2),
    line_coinsrnc_amt_11  NUMERIC(12,2),
    line_coinsrnc_amt_12  NUMERIC(12,2),
    line_coinsrnc_amt_13  NUMERIC(12,2),

    line_alowd_chrg_amt_1   NUMERIC(12,2),
    line_alowd_chrg_amt_2   NUMERIC(12,2),
    line_alowd_chrg_amt_3   NUMERIC(12,2),
    line_alowd_chrg_amt_4   NUMERIC(12,2),
    line_alowd_chrg_amt_5   NUMERIC(12,2),
    line_alowd_chrg_amt_6   NUMERIC(12,2),
    line_alowd_chrg_amt_7   NUMERIC(12,2),
    line_alowd_chrg_amt_8   NUMERIC(12,2),
    line_alowd_chrg_amt_9   NUMERIC(12,2),
    line_alowd_chrg_amt_10  NUMERIC(12,2),
    line_alowd_chrg_amt_11  NUMERIC(12,2),
    line_alowd_chrg_amt_12  NUMERIC(12,2),
    line_alowd_chrg_amt_13  NUMERIC(12,2),

    line_prcsg_ind_cd_1   CHAR(1),
    line_prcsg_ind_cd_2   CHAR(1),
    line_prcsg_ind_cd_3   CHAR(1),
    line_prcsg_ind_cd_4   CHAR(1),
    line_prcsg_ind_cd_5   CHAR(1),
    line_prcsg_ind_cd_6   CHAR(1),
    line_prcsg_ind_cd_7   CHAR(1),
    line_prcsg_ind_cd_8   CHAR(1),
    line_prcsg_ind_cd_9   CHAR(1),
    line_prcsg_ind_cd_10  CHAR(1),
    line_prcsg_ind_cd_11  CHAR(1),
    line_prcsg_ind_cd_12  CHAR(1),
    line_prcsg_ind_cd_13  CHAR(1),

    line_icd9_dgns_cd_1   VARCHAR(5),
    line_icd9_dgns_cd_2   VARCHAR(5),
    line_icd9_dgns_cd_3   VARCHAR(5),
    line_icd9_dgns_cd_4   VARCHAR(5),
    line_icd9_dgns_cd_5   VARCHAR(5),
    line_icd9_dgns_cd_6   VARCHAR(5),
    line_icd9_dgns_cd_7   VARCHAR(5),
    line_icd9_dgns_cd_8   VARCHAR(5),
    line_icd9_dgns_cd_9   VARCHAR(5),
    line_icd9_dgns_cd_10  VARCHAR(5),
    line_icd9_dgns_cd_11  VARCHAR(5),
    line_icd9_dgns_cd_12  VARCHAR(5),
    line_icd9_dgns_cd_13  VARCHAR(5)
);
DROP TABLE IF EXISTS beneficiaries;
CREATE TABLE beneficiaries (
    desynpuf_id CHAR(16),
    bene_birth_dt CHAR(8),
    bene_death_dt CHAR(8),
    bene_sex_ident_cd SMALLINT,
    bene_race_cd SMALLINT,
    bene_esrd_ind CHAR(1),
    sp_state_code SMALLINT,
    bene_county_cd VARCHAR(3),
    bene_hi_cvrage_tot_mons SMALLINT,
    bene_smi_cvrage_tot_mons SMALLINT,
    bene_hmo_cvrage_tot_mons SMALLINT,
    plan_cvrg_mos_num SMALLINT,
    sp_alzhdmta SMALLINT,
    sp_chf SMALLINT,
    sp_chrnkidn SMALLINT,
    sp_cncr SMALLINT,
    sp_copd SMALLINT,
    sp_depressn SMALLINT,
    sp_diabetes SMALLINT,
    sp_ischmcht SMALLINT,
    sp_osteoprs SMALLINT,
    sp_ra_oa SMALLINT,
    sp_strketia SMALLINT,
    medreimb_ip NUMERIC(12,2),
    benres_ip NUMERIC(12,2),
    pp_pymt_ip NUMERIC(12,2),
    medreimb_op NUMERIC(12,2),
    benres_op NUMERIC(12,2),
    pp_pymt_op NUMERIC(12,2),
    medreimb_car NUMERIC(12,2),
    benres_car NUMERIC(12,2),
    pp_pymt_car NUMERIC(12,2)
);

SELECT * FROM carrier_claims
LIMIT 10;